default: &default
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  pool: 10
  username: root
  password:

development:
  <<: *default
  # database: db/development.sqlite3
  database: global_db_development

# test:
#   <<: *default
#   database: db/test.sqlite3

staging:
  <<: *default
  database: global_db_staging
  adapter: mysql2
  port: 3306

production:
  <<: *default
  adapter:  mysql2
  encoding: utf8
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host:     <%= ENV['DB_HOSTNAME'] %>
  port:     <%= ENV['DB_PORT'] %>
