default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: global_db_development

test:
  <<: *default
  adapter: sqlite3
  database: global_db_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
