default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3
# test:
#   <<: *default
#   database: db/test.sqlite3

staging:
  <<: *default
  database: global_db_staging
  adapter: mysql2
  port: 3306

# production:
#   <<: *default
#   database: db/production.sqlite3
