default: &default
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  pool: 10
  username: 'samurai'
  password: 'samurai'

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3
# test:
#   <<: *default
#   database: db/test.sqlite3

staging:
  <<: *default
  database: global_db_staging
  adapter: mysql2
  port: 3306

production:
  <<: *default
  adapter: mysql2
  port: 3306
  database: mysql2
