default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: kyuma
  password:
  pool: 5

development:
  <<: *default
  database: global_db_development

test:
  <<: *default
  database: global_db_test
